"""initial_schema

Revision ID: 500d7d9045bc
Revises: 
Create Date: 2026-03-11 18:51:51.163761

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '500d7d9045bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('parent_entity_type', sa.String(length=20), nullable=True),
    sa.Column('parent_entity_id', sa.UUID(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_status', 'documents', ['processing_status'], unique=False)
    op.create_table('llm_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('schema_name', sa.String(length=100), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_family', sa.String(length=50), nullable=False),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_specs', 'products', ['specs'], unique=False, postgresql_using='gin')
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('contractor', sa.String(length=255), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenders_reqs', 'tenders', ['requirements'], unique=False, postgresql_using='gin')
    op.create_table('compliance_comparisons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_components',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('component_tag', sa.String(length=50), nullable=True),
    sa.Column('component_type', sa.String(length=50), nullable=True),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_requirements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('source_section', sa.String(length=50), nullable=True),
    sa.Column('extracted_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tender_reqs_category', 'tender_requirements', ['category'], unique=False)
    op.create_table('compliance_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('product_value', sa.Text(), nullable=True),
    sa.Column('tender_value', sa.Text(), nullable=True),
    sa.Column('gap_description', sa.Text(), nullable=True),
    sa.Column('modification_needed', sa.Text(), nullable=True),
    sa.Column('estimated_cost_delta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['comparison_id'], ['compliance_comparisons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compliance_items_status', 'compliance_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_compliance_items_status', table_name='compliance_items')
    op.drop_table('compliance_items')
    op.drop_index('idx_tender_reqs_category', table_name='tender_requirements')
    op.drop_table('tender_requirements')
    op.drop_table('product_components')
    op.drop_table('document_chunks')
    op.drop_table('compliance_comparisons')
    op.drop_index('idx_tenders_reqs', table_name='tenders', postgresql_using='gin')
    op.drop_table('tenders')
    op.drop_index('idx_products_specs', table_name='products', postgresql_using='gin')
    op.drop_table('products')
    op.drop_table('llm_cache')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
